Mecha_table <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
library(dplyr)
library(tidyverse)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=Mecha_table) 
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=Mecha_table))
Suspension_table <- read.csv(file='Suspension_Coil.csv',check.names = F, stringsAsFactors = F)
total_summary <- Suspension_table %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep'))
total_summary <- Suspension_table %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep')
lot_summary <- Suspension_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep')
lot_sample <- Suspension_table %>% sample_n(50)
t.test(lot_sample$PSI,mu=mean(Suspension_table$PSI))
lot1_sample <- Suspension_table %>% subset(Manufacturing_Lot=='Lot1') %>% sample_n(20)
lot2_sample <- Suspension_table %>% subset(Manufacturing_Lot=='Lot2') %>% sample_n(20)
lot3_sample <- Suspension_table %>% subset(Manufacturing_Lot=='Lot3') %>% sample_n(20)
t.test(lot1_sample$PSI,mu=mean(Suspension_table$PSI))
t.test(lot2_sample$PSI,mu=mean(Suspension_table$PSI))
t.test(lot3_sample$PSI,mu=mean(Suspension_table$PSI))